### ISSUE TITLE
03-24-Scrum Meeting Notes

### ISSUE THREAD

**Issue by AjFroster** [SeanWallach/SYSC-4806#46]

**Comment by AjFroster** [comment]
What I did: Created a way to identify a current active user, and add books based on their ISBN to their cart when on the userHomepage while browing the book library.
What I will do: Implement a purchase feature, based on all the books + selected quantity in the clients cart.
What is blocking me: The cart is displayed on the same page as the book library, so every time a new book is added to the cart, the quantities are reset. Might need to add cart to a different page.

**Comment by EverettSoldaat** [comment]
What I did: Add image upload to create book form
What I will do: Add images to user homepage, create UML and DB Schema, additional tests.
What is blocking me: Creating UML once all other features complete.

**Comment by adybka** [comment]
what I did: Set up documentation for how to use and access deployment database and local database. Created ownerHome Page displaying books in store each with an edit button and implement edit functionality. Also add button on owner homepage to navigate add book page
what i will do: PostgREST implementation

**Comment by SeanWallach** [comment]
**What I did:** Not much since last meeting, was focused on other school projects
**What I will do:** Owner Homepage modifications: try and filter books by their publisher so that it matches the current owner. Adjust some table/button text
**What is blocking me:** Possibly how we keep track of which user/owner is currently logged in
